spring:
  application:
    name: myapp
  datasource:
    url: jdbc:mysql://localhost:3306/summarizer
    username: root
    password: Tfovygv$185956
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# Configurazione servizio NLP Python (black box)
nlp:
  service:
    url: http://localhost:8000